app/main/routes/about.py
from flask import Blueprint, render_template

about = Blueprint('about', __name__)

@about.route('/')
def home():
    return render_template('about.html', title="About")

app/main/routes/cart.py
from flask import Blueprint
from ..services.cart_services import *
import json


cart = Blueprint('cart', __name__)

@cart.route('/')
def home():
    return "Welcome to your cart"


@cart.route('/add', methods=['POST'])
def new_cart():
    result = add_cart()
    if result:
        return json.dumps({
            "message": "Cart added successfully",
            "status": True
        })
    else:
       return json.dumps({
            "message": "Error while adding cart",
            "status": False
        })


@cart.route('/view', methods=['GET'])
def show_cart():
    carts = view_cart()
    output = []
    for row in carts:
        item = {}
        item['product_name'] = row['name']
        item['price'] = row['price']
        item['date'] = str(row['date'])
        output.append(item)
    return json.dumps({
        "message": output,
            "status": True
    })

app/main/routes/user.py
from flask import Blueprint, render_template, session, url_for
from ..services.user_services import *
from ..forms.forms import LoginForm, RegisterForm
import json


user = Blueprint('user', __name__)

@user.route('/')
def home():
    return render_template("index.html")


@user.route('/add', methods=['GET','POST'])
def new_user():
    # result = add_user()
    form = RegisterForm()
    if form.validate_on_submit():
        result = add_user(form)
        output = json.loads(result)
        if output["status"] == True:
            message = output["message"]
            category = output["category"]
            flash(message, category)
            return redirect('/')
        else:
            message = output["message"]
            category = output["category"]
            flash(message, category)
    return render_template("register.html", title="Sign Up", form=form)


@user.route('/login', methods=['GET','POST'])
def user_login():
    # result = login()
    if session.get('user_name'):
        return redirect('/')

    form = LoginForm()
    if form.validate_on_submit():
        result = login(form)
        output = json.loads(result)
        if output["status"] == True:
            message = output["message"]
            category = output["category"]
            flash(message, category)
            session['user_id'] = output["user_id"]
            session['user_name'] = output["user_name"]
            session['user_type'] = output["user_type"]
            session['user_mobile'] = output["user_mobile"]
            session['user_email'] = output["user_email"]
            return redirect('/')
        else:
            message = output["message"]
            category = output["category"]
            flash(message, category)
    return render_template("login.html", title="Sign In", form=form)

@user.route("/logout", methods=["POST", "GET"])
def user_logout():
    session["user_name"] = False
    session.pop("user_id", None)
    session.pop("user_type", None)
    return redirect('/')

@user.route("/profile", methods=["POST", "GET"])
def user_profile():
    if not session.get('user_name'):
        return redirect(url_for('user.user_login'))
    
    return render_template("profile.html", title="My Account")

app/main/templates/includes/footer.html
<!-- info section -->
<section class="info_section ">
        <div class="container">
          <div class="row">
            <div class="col-md-3">
              <div class="info_contact">
                <h5>
                  <a href="" class="navbar-brand">
                    <span>
                      Minics
                    </span>
                  </a>
                </h5>
                <p>
                  <i class="fa fa-map-marker" aria-hidden="true"></i>
                  Address
                </p>
                <p>
                  <i class="fa fa-phone" aria-hidden="true"></i>
                  +01 1234567890
                </p>
                <p>
                  <i class="fa fa-envelope" aria-hidden="true"></i>
                  demo@gmail.com
                </p>
              </div>
            </div>
            <div class="col-md-3">
              <div class="info_info">
                <h5>
                  Information
                </h5>
                <p>
                  Eligendi sunt, provident, debitis nemo, facilis cupiditate velit libero dolorum aperiam enim nulla iste maxime corrupti ad illo libero minus.
                </p>
              </div>
            </div>
            <div class="col-md-3">
              <div class="info_links">
                <h5>
                  Useful Link
                </h5>
                <ul>
                  <li>
                    <a href="index.html">
                      Home
                    </a>
                  </li>
                  <li>
                    <a href="about.html">
                      About
                    </a>
                  </li>
                  <li>
                    <a href="product.html">
                      Products
                    </a>
                  </li>
                  <li>
                    <a href="why.html">
                      Why Us
                    </a>
                  </li>
                  <li>
                    <a href="testimonial.html">
                      Testimonial
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3">
              <div class="info_form ">
                <h5>
                  Newsletter
                </h5>
                <form action="">
                  <input type="email" placeholder="Enter your email">
                  <button>
                    Subscribe
                  </button>
                </form>
                <div class="social_box">
                  <a href="">
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                  </a>
                  <a href="">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                  </a>
                  <a href="">
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                  </a>
                  <a href="">
                    <i class="fa fa-youtube" aria-hidden="true"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    
      <!-- end info_section -->
    
    
      <!-- footer section -->
      <footer class="footer_section">
        <div class="container">
          <p>
            &copy; <span id="displayYear"></span> All Rights Reserved By
            <a href="https://html.design/">Free Html Templates</a>
          </p>
        </div>
      </footer>
      <!-- footer section -->

app/main/templates/includes/header.html
<!-- header section strats -->
<header class="header_section">
    <div class="header_top">
      <div class="container-fluid">
        <div class="top_nav_container">
          <div class="contact_nav">
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Call : +01 123455678990
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                Email : demo@gmail.com
              </span>
            </a>
          </div>
          <from class="search_form">
            <input type="text" class="form-control" placeholder="Search here...">
            <button class="" type="submit">
              <i class="fa fa-search" aria-hidden="true"></i>
            </button>
          </from>
          <div class="user_option_box">
            <!-- <a href="{{ url_for('user.user_login') }}" class="account-link"> -->
            <a href="{{ url_for('user.user_profile') }}" class="account-link">
              <i class="fa fa-user" aria-hidden="true"></i>
              <span>
                My Account
              </span>
            </a>
            {% if session['user_name'] %}
              <a href="{{ url_for('user.user_logout') }}" class="account-link">
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <span>
                    Sign Out
                  </span>
                </a>
            {% endif %}
            <a href="{{ url_for('cart.show_cart') }}" class="cart-link">
              <i class="fa fa-shopping-cart" aria-hidden="true"></i>
              <span>
                Cart
              </span>
            </a>
          </div>
        </div>

      </div>
    </div>
    <div class="header_bottom">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <span>
              Minics
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ">
              <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('home') }}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('about.home') }}"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="product.html">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="why.html">Why Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="testimonial.html">Testimonial</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <!-- end header section -->