app/main/routes/about.py
from flask import Blueprint, render_template

about = Blueprint('about', __name__)

@about.route('/')
def home():
    return render_template('about.html', title="About")

app/main/routes/user.py
from flask import Blueprint, render_template, session, url_for
from ..services.user_services import *
from ..forms.forms import LoginForm, RegisterForm
import json


user = Blueprint('user', __name__)

@user.route('/')
def home():
    return render_template("index.html")


@user.route('/add', methods=['GET','POST'])
def new_user():
    # result = add_user()
    form = RegisterForm()
    if form.validate_on_submit():
        result = add_user(form)
        output = json.loads(result)
        if output["status"] == True:
            message = output["message"]
            category = output["category"]
            flash(message, category)
            return redirect('/')
        else:
            message = output["message"]
            category = output["category"]
            flash(message, category)
    return render_template("register.html", title="Sign Up", form=form)


@user.route('/login', methods=['GET','POST'])
def user_login():
    # result = login()
    if session.get('user_name'):
        return redirect('/')

    form = LoginForm()
    if form.validate_on_submit():
        result = login(form)
        output = json.loads(result)
        if output["status"] == True:
            message = output["message"]
            category = output["category"]
            flash(message, category)
            session['user_id'] = output["user_id"]
            session['user_name'] = output["user_name"]
            session['user_type'] = output["user_type"]
            session['user_mobile'] = output["user_mobile"]
            session['user_email'] = output["user_email"]
            return redirect('/')
        else:
            message = output["message"]
            category = output["category"]
            flash(message, category)
    return render_template("login.html", title="Sign In", form=form)

@user.route("/logout", methods=["POST", "GET"])
def user_logout():
    session["user_name"] = False
    session.pop("user_id", None)
    session.pop("user_type", None)
    return redirect('/')

@user.route("/profile", methods=["POST", "GET"])
def user_profile():
    if not session.get('user_name'):
        return redirect(url_for('user.user_login'))
    
    return render_template("profile.html", title="My Account")

app/main/templates/about.html
{% extends "layout.html" %}
  
{% block content %}

  <section class="about_section">
    <div class="container-fluid  ">
      <div class="row">
        <div class="col-md-5 ml-auto">
          <div class="detail-box pr-md-3">
            <div class="heading_container">
              <h2>
                We Provide Best For You
              </h2>
            </div>
            <p>
              Totam architecto rem beatae veniam, cum officiis adipisci soluta perspiciatis ipsa, expedita maiores quae accusantium. Animi veniam aperiam, necessitatibus mollitia ipsum id optio ipsa odio ab facilis sit labore officia!
              Repellat expedita, deserunt eum soluta rem culpa. Aut, necessitatibus cumque. Voluptas consequuntur vitae aperiam animi sint earum, ex unde cupiditate, molestias dolore quos quas possimus eveniet facilis magnam? Vero, dicta.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6 px-0">
          <div class="img-box">
            <img src="images/about-img.jpg" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

{% endblock %}

app/main/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="../static/images/fevicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Minics</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link href="../static/css/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="../static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="../static/css/responsive.css" rel="stylesheet" />

</head>

<body>

  <div class="hero_area">

    {% include "includes/header.html" %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <p>{{ message }}</p>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock %}



    {% include "includes/footer.html" %}

    <!-- jQery -->
    <script src="../static/js/jquery-3.4.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="../static/js/bootstrap.js"></script>
    <!-- custom js -->
    <script src="../static/js/custom.js"></script>
  
  
  </body>
  
  </html>

app/main/templates/login-new.html
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
		<div class="login-form">
			<div class="sign-in-htm">
				<div class="group">
					<label for="user" class="label">Username</label>
					<input id="user" type="text" class="input">
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<input id="check" type="checkbox" class="check" checked>
					<label for="check"><span class="icon"></span> Keep me Signed in</label>
				</div>
				<div class="group">
					<input type="submit" class="button" value="Sign In">
				</div>
				<div class="hr"></div>
				<div class="foot-lnk">
					<a href="#forgot">Forgot Password?</a>
				</div>
			</div>
			<div class="sign-up-htm">
				<div class="group">
					<label for="user" class="label">Username</label>
					<input id="user" type="text" class="input">
				</div>
				<div class="group">
					<label for="pass" class="label">Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<label for="pass" class="label">Repeat Password</label>
					<input id="pass" type="password" class="input" data-type="password">
				</div>
				<div class="group">
					<label for="pass" class="label">Email Address</label>
					<input id="pass" type="text" class="input">
				</div>
				<div class="group">
					<input type="submit" class="button" value="Sign Up">
				</div>
				<div class="hr"></div>
				<div class="foot-lnk">
					<label for="tab-1">Already Member?</a>
				</div>
			</div>
		</div>
	</div>
</div>

app/main/templates/login.html
{% extends "layout.html" %}
  
{% block content %}

<div class="login-wrap">
    <div class="login-html">
        <div class="login-form">
            <div class="sign-in-htm">
                <div class="group">
                    <form method="post" action="" novalidate>
                        <fieldset class="group">
                            <legend class="sign-up tab">{{ title }}</legend>
                            {{ form.hidden_tag() }}
                            <div class="group label">
                                {{ form.email.label }} <br>
                                {{ form.email(size=25) }}
                            </div>
                            <div class="group label">
                                {{ form.password.label }} <br>
                                {{ form.password(size=25) }}
                            </div>
                            <div class="group sign-in">
                                {{ form.remember_me }} {{ form.remember_me.label }}
                            </div>
                            <div class="group">
                                {{ form.submit(class="button") }} 
                            </div>
                            <div class="group sign-in">
                                <p>New User? <a href="{{ url_for('user.new_user')}}">Sign Up</a> here.</p>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/main/templates/profile.html
{% extends "layout.html" %}
  
{% block content %}
<link href="../static/css/profile-style.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container bootstrap snippets bootdey">
<div class="row">
  <div class="profile-nav col-md-3">
      <div class="panel">
          <div class="user-heading round">
              <a href="#">
                  <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="">
              </a>
              <h1>{{ session["user_name"] }}</h1>
              <p>{{ session["user_email"] }}</p>
          </div>

          <ul class="nav nav-pills nav-stacked">
              <li class="active"><a href="#"> <i class="fa fa-user"></i> Profile</a></li>
              <li><a href="#"> <i class="fa fa-calendar"></i> Recent Activity <span class="label label-warning pull-right r-activity">9</span></a></li>
              <li><a href="#"> <i class="fa fa-edit"></i> Edit profile</a></li>
          </ul>
      </div>
  </div>
  <div class="profile-info col-md-9">
     
      <div class="panel">
          
          <div class="panel-body bio-graph-info">
              <h1>{{ title }}</h1>
              <div class="row">
                  <div class="bio-row">
                      <p><span> Name </span>: {{ session["user_name"] }}</p>
                  </div>
                  <!-- <div class="bio-row">
                      <p><span>Last Name </span>: Smith</p>
                  </div>
                  <div class="bio-row">
                      <p><span>Country </span>: Australia</p>
                  </div>
                  <div class="bio-row">
                      <p><span>Birthday</span>: 13 July 1983</p>
                  </div>
                  <div class="bio-row">
                      <p><span>Occupation </span>: UI Designer</p>
                  </div> -->
                  <div class="bio-row">
                      <p><span>Email </span>: {{ session["user_email"] }}</p>
                  </div>
                  <div class="bio-row">
                      <p><span>Mobile </span>: {{ session["user_mobile"] }}</p>
                  </div>
                  <!-- <div class="bio-row">
                      <p><span>Phone </span>: 88 (02) 123456</p>
                  </div> -->
              </div>
          </div>
      </div>
      </div>
  </div>
</div>
</div>
{% endblock %}

app/main/templates/register.html
{% extends "layout.html" %}
  
{% block content %}
        <div class="login-wrap">
            <div class="login-html">
                <div class="login-form">
                    <div class="sign-up-htm">
                        <div class="group">
                            <form method="post" action="" novalidate>
                                <fieldset class="group">
                                    <legend class="sign-up tab">{{ title }}</legend>
                                    {{ form.hidden_tag() }}
                                    <div class="group">
                                        <div class="label">
                                            {{ form.user_name.label }} <br>
                                            {{ form.user_name(size=30) }}
                                        </div>
                                        {% for error in form.user_name.errors %}
                                            <small class="text-danger">
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                    <div class="group">
                                        <div class="label">
                                            {{ form.mobile.label }} <br>
                                            {{ form.mobile(size=30) }}
                                        </div>
                                        {% for error in form.mobile.errors %}
                                            <small class="text-danger">
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                    <div class="group">
                                        <div class="label">
                                            {{ form.email.label }} <br>
                                            {{ form.email(size=30) }}
                                        </div>
                                        {% for error in form.email.errors %}
                                            <small class="text-danger">
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                    <div class="group">
                                        <div class="label">
                                            {{ form.password.label }} <br>
                                            {{ form.password(size=30) }}
                                        </div>
                                        {% for error in form.password.errors %}
                                            <small class="text-danger">
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                    <div class="group">
                                        <div class="label">
                                            {{ form.confirm_password.label }} <br>
                                            {{ form.confirm_password(size=30) }}
                                        </div>
                                        {% for error in form.confirm_password.errors %}
                                            <small class="text-danger">
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                    <div class="group">
                                            {{ form.submit(class="button") }}
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

app/main/templates/testimonial.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="images/fevicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Minics</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link href="css/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="top_nav_container">
            <div class="contact_nav">
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call : +01 123455678990
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  Email : demo@gmail.com
                </span>
              </a>
            </div>
            <from class="search_form">
              <input type="text" class="form-control" placeholder="Search here...">
              <button class="" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </from>
            <div class="user_option_box">
              <a href="" class="account-link">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>
                  My Account
                </span>
              </a>
              <a href="" class="cart-link">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span>
                  Cart
                </span>
              </a>
            </div>
          </div>

        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="index.html">
              <span>
                Minics
              </span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item ">
                  <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="about.html"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="product.html">Products</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="why.html">Why Us</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="testimonial.html">Testimonial</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!-- end header section -->
  </div>



  <!-- client section -->

  <section class="client_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          What Says Our Customers
        </h2>
      </div>
    </div>
    <div class="client_container ">
      <div id="carouselExample2Controls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="client-id">
                  <div class="img-box">
                    <img src="images/client.jpg" alt="">
                  </div>
                  <div class="name">
                    <h5>
                      James Dew
                    </h5>
                    <h6>
                      Photographer
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="client-id">
                  <div class="img-box">
                    <img src="images/client.jpg" alt="">
                  </div>
                  <div class="name">
                    <h5>
                      James Dew
                    </h5>
                    <h6>
                      Photographer
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="client-id">
                  <div class="img-box">
                    <img src="images/client.jpg" alt="">
                  </div>
                  <div class="name">
                    <h5>
                      James Dew
                    </h5>
                    <h6>
                      Photographer
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="carousel_btn-box">
          <a class="carousel-control-prev" href="#carouselExample2Controls" role="button" data-slide="prev">
            <span>
              <i class="fa fa-angle-left" aria-hidden="true"></i>
            </span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExample2Controls" role="button" data-slide="next">
            <span>
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </section>
  <!-- end client section -->

  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  Minics
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Address
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              +01 1234567890
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              demo@gmail.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
              Eligendi sunt, provident, debitis nemo, facilis cupiditate velit libero dolorum aperiam enim nulla iste maxime corrupti ad illo libero minus.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              Useful Link
            </h5>
            <ul>
              <li>
                <a href="index.html">
                  Home
                </a>
              </li>
              <li>
                <a href="about.html">
                  About
                </a>
              </li>
              <li>
                <a href="product.html">
                  Products
                </a>
              </li>
              <li>
                <a href="why.html">
                  Why Us
                </a>
              </li>
              <li>
                <a href="testimonial.html">
                  Testimonial
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <h5>
              Newsletter
            </h5>
            <form action="">
              <input type="email" placeholder="Enter your email">
              <button>
                Subscribe
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->


  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="js/jquery-3.4.1.min.js"></script>
  <!-- bootstrap js -->
  <script src="js/bootstrap.js"></script>
  <!-- custom js -->
  <script src="js/custom.js"></script>


</body>

</html>